### ISSUE TITLE
Sechud randomly stops displaying icons temporary, repeatly 

### ISSUE THREAD

**Issue by MeowVal** [DeltaV-Station/Delta-v#1011] opened 2024-03-27 04:16 UTC
## Description

The sechud overlay keeps on randomly not working. By that I mean the sechud randomly does not show icons etc and its temporary but keeps coming back. 

**Reproduction**
Equip a sechud, run around near other people and watch the hud icons disappear and reappear. 

**Screenshots**
![image](https://github.com/DeltaV-Station/Delta-v/assets/46445294/c3fb44b3-788e-457b-be8d-3e0057097df6)
![20240327050302_1](https://github.com/DeltaV-Station/Delta-v/assets/46445294/e66cdfd5-9c13-4757-95aa-cc37ef1b8ebe)
![20240327050303_1](https://github.com/DeltaV-Station/Delta-v/assets/46445294/d26bbc63-1450-4af0-b643-d66c557297f0)
![20240327052703_1](https://github.com/DeltaV-Station/Delta-v/assets/46445294/8917ffcf-1a4a-4b8d-97bf-7a93d7aa2b89)

**Additional context**
The screenshots clearly show me just walking up and down getting the bug, you can even see that I have the sechud equipped also it keeps spamming the logs with an error from the clyde.overlay as shown in the screenshot. It's so fast that the console log can not keep up.
Seems to be a System.NullReferenceException in the code from the logs. I don't know how to print the client logs but I have attached a screenshot.

My platform is windows

Edit: Added another screenshot
Edit two: spelling and gramma plus a bit more info

**Comment by Adrian16199** [comment] 2024-04-03 13:26
This issue has been fixed.
As the screenshot can show, delta V/nyano job icons are visible which was the cause of the hud just *dying*. It should be fixed the next time the server updates.

(Hopefully)

**Closed as completed** 2024-07-01 18:50 UTC
