### ISSUE TITLE
psionic invisibility issues

### ISSUE THREAD

**Issue by deltanedas** [DeltaV-Station/Delta-v#1885] opened 2024-09-21 05:34 UTC
## Description
- you have no action to cancel invisiblity, #644
- when you are invisible your client doesnt think your inventory item or held items exist for some reason

if these are fixed the power can be readded, it works as expected from the pov of other players

**Comment by MilonPL** [comment] 2024-09-23 18:07
Up to the @DeltaV-Station/game-directors if that's something we want to bring back.

**Comment by TadJohnson00** [comment] 2024-09-24 16:20
duplicate of previous issue, and also not something we'll be bringing back in the state that it previously was in.

**Comment by MilonPL** [comment] 2024-09-24 16:21
wrong button ops

**Closed as not planned by TadJohnson00** 2024-09-24 16:20 UTC
Labels: Priority: 3-Medium, S: Legacy Code
