### ISSUE TITLE
Psionic power Mass Sleep does not work

### ISSUE THREAD

**Issue by dekigangsta** [DeltaV-Station/Delta-v#1478] opened 2024-07-10 13:03 UTC
## Description
The psionic power mass sleep should be considered one of best traits for syndicates when it comes to killing someone or stealing from somebody although it currently is one of worst psionic powers to have since it does not function how it should originally function.

When you use the power, it DOES put the target to sleep but they wake up 1 second after, this may be tilting for any syndicates who do not know about this "bug".

**Reproduction**
Get Mass Sleep power, use on anyone

**Screenshots**
![powernap-ezgif com-video-to-gif-converter(1)](https://github.com/DeltaV-Station/Delta-v/assets/175221516/3e1d20fd-fc89-412f-91fe-abcf416196d9)

**Comment by DangerRevolution** [comment] 2024-07-10 15:09
Duplicate of #1433

Should probably be disabled...

**Closed as not planned** 2024-07-10 15:54 UTC
Labels: S: Untriaged
