### ISSUE TITLE
some hammurabi issues

### ISSUE THREAD

**Issue by deltanedas** [DeltaV-Station/Delta-v#692] opened 2024-01-18 21:25 UTC
## Description
1. one of the escape pod station-side doors is unpowered northwest ish
2. cryo pod setup is a joke:
- volumepump lmao
- filters will clog since they do not filter 1 combined pipenet see saltern for example that does it right
- no need for 3 filters only nox and co2
3. apparently it still has a plasma miner
4. no teg /!\
5. need to colornetwork waste and maybe distro

**Comment by IamVelcroboy** [comment] 2024-01-18 21:45
Volume pump is key for cryopod (ok maybe not. But I seem to remember you can over-pressurize and kill the person inside w/out it.)
I don't understand the clog comment...please elaborate.
3rd filter is an option if you want to just dump it into waste network instead of filling canisters.

Def does not have a plasma miner
![image](https://github.com/DeltaV-Station/Delta-v/assets/107660393/499a740b-98bc-4bc2-933c-979a27b9e49b)

Singulo means no TEG

Just ran colornetwork in the last update(has not published yet)

**Comment by deltanedas** [comment] 2024-01-18 22:10
> over-pressurize and kill the person inside w/out it.)

opposite
volume will keep pumping up to 9mpa, gas pump will only pump up to what you set it

to prevent clog the filter inlet and outlet need to be the same pipenet. loop it around each filter or just put a straight pipe across them

i dont know why you would want to filter like 0.5 mols of nox into a can. makes more sense to just always go to waste

**Comment by IamVelcroboy** [comment] 2024-01-18 22:40
> opposite volume will keep pumping up to 9mpa, gas pump will only pump up to what you set it
 
 hmm, ok. 
 
> to prevent clog the filter inlet and outlet need to be the same pipenet. loop it around each filter or just put a straight pipe across them

they are on the same net. 

> i dont know why you would want to filter like 0.5 mols of nox into a can. makes more sense to just always go to waste

I like to give options.

**Comment by deltanedas** [comment] 2024-01-18 22:52
> they are on the same net.

they are not

main part -> filter 1 -> filter 2 -> filter 3 -> main part

it needs to be main part inbetween each filter, so use pipe

**Comment by IamVelcroboy** [comment] 2024-01-18 23:11
> it needs to be main part inbetween each filter, so use pipe

Hmm, I don't know about that. I've tested it myself and used it in-game. I've never had a problem with filters being connected before. It's not the only map that has them like that, either in atmos or  cryo

**Comment by IamVelcroboy** [comment] 2024-01-18 23:34
Not to be completely contrary with you, deltanedas, I appreciate the feedback. Just hasn't been an issue from my experience. If you can demonstrate it or if you run into issues during round to show an example, I will address it. For now, I'm pretty sure it's ok though.

**Comment by deltanedas** [comment] 2024-01-19 12:12
on hive a cmo couldnt understand why cryo was dying, then i added pipes along the filters and it worked perfectly

with gas pump you can just leave it on always, dont need to babysit it to make sure you dont overpressurise

**Comment by IamVelcroboy** [comment] 2024-01-25 00:38
> on hive a cmo couldnt understand why cryo was dying, then i added pipes along the filters and it worked perfectly

If this happens again and you can demonstrate the current setup is not functioning as intended, open the issue again and I'll look into it. But it works fine when I test it. So, I'm closing for now.

> with gas pump you can just leave it on always, dont need to babysit it to make sure you dont overpressurise

The pump was changed in the last update.
Everything else was fixed.

**Closed as completed by IamVelcroboy** 2024-01-25 00:38 UTC
